GET http://localhost:3000/project/d20543f0-e7a3-11ee-bac1-d9e39a2d8f32

###

POST http://localhost:3000/project
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImJpb2dyYXBoeSI6bnVsbCwiZXhwZXJpZW5jZSI6MCwiaXNfdmVyaWZpZWQiOjAsImlzX2Jhbm5lZCI6MCwiaXNfYWRtaW4iOjAsInR3aXR0ZXIiOm51bGwsImluc3RhZ3JhbSI6bnVsbCwidGlrdG9rIjpudWxsLCJ5b3V0dWJlIjpudWxsLCJpYXQiOjE3MTA5NTQ0OTV9.Pu9_HVt8Twqk07IaQ2DhylsqnIqq8GV7ssKKxLDQMnU

{
    "title": "For lack of a better name",
    "imageData": []
}

###

PUT http://localhost:3000/project/5
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImJpb2dyYXBoeSI6bnVsbCwiZXhwZXJpZW5jZSI6MCwiaXNfdmVyaWZpZWQiOjAsImlzX2Jhbm5lZCI6MCwiaXNfYWRtaW4iOjAsInR3aXR0ZXIiOm51bGwsImluc3RhZ3JhbSI6bnVsbCwidGlrdG9rIjpudWxsLCJ5b3V0dWJlIjpudWxsLCJpYXQiOjE3MTA5NTQ0OTV9.Pu9_HVt8Twqk07IaQ2DhylsqnIqq8GV7ssKKxLDQMnU

{
    "projectData": { }
}